ARG NODE_VERSION=24-alpine
FROM node:${NODE_VERSION} AS base
WORKDIR /app
ARG PNPM_VERSION=9.15.9
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/server/package.json ./apps/server/
COPY apps/web/package.json ./apps/web/
COPY packages/ova-cli/package.json ./packages/ova-cli/

RUN pnpm install --frozen-lockfile

COPY apps/server ./apps/server
COPY packages/ova-cli ./packages/ova-cli

RUN pnpm --filter server run build

EXPOSE 6001

WORKDIR /app/apps/server
CMD ["node", "dist/main"]
