FROM node:20-alpine AS base
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@8.15.9 --activate

COPY package.json pnpm-workspace.yaml ./
COPY apps/web/package.json ./apps/web/

RUN pnpm install --no-frozen-lockfile

COPY apps/web ./apps/web

RUN pnpm --filter web run build

EXPOSE 6002

CMD ["pnpm", "--filter", "web", "run", "start"]
