FROM node:20-alpine AS base
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@8.15.9 --activate

COPY package.json pnpm-workspace.yaml ./
COPY apps/server/package.json ./apps/server/
COPY packages/ova-cli/package.json ./packages/ova-cli/

RUN pnpm install --no-frozen-lockfile

COPY apps/server ./apps/server
COPY packages/ova-cli ./packages/ova-cli

RUN pnpm --filter server run build

EXPOSE 6001

CMD ["pnpm", "--filter", "server", "run", "start:prod"]
